version: '3.1'
networks:
  mynetwork:
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/letsencrypt:/etc/nginx/snippets/letsencrypt
    ports:
      - 80:80
      - 443:443

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    networks:
      mynetwork:
        aliases:
          - mosquitto
    ports:
      - "1883:1883"

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Paris
    networks:
      mynetwork:
        aliases:
          - node-red

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: weather
      MYSQL_USER: weather
      MYSQL_PASSWORD: weather
      MYSQL_ROOT_PASSWORD: Jmpfricpiud
    networks:
      mynetwork:
        aliases:
          - mysql

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      mynetwork:
        aliases:
          - grafana
    volumes:
      - ./grafana/dashboards:/conf/provisioning/dasboards
      - ./grafana/datasources:/conf/provisioning/datasources
      - ./grafana-storage/:/var/lib/grafana
    user: "root"

  ubuntu-update:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      mynetwork:
        aliases:
          - update
    environment:
      - PASSWORD=$PASSWORD
      - MOSQUITTO_HOST=$MOSQUITTO_HOST
      - MOSQUITTO_LOGIN=$MOSQUITTO_LOGIN
      - MOSQUITTO_LOG_FILE=$MOSQUITTO_LOG_FILE
      - NODE_HOST=$NODE_HOST
      - NODE_LOGIN=$NODE_HOST_LOGIN
      - NODE_LOG_FILE=$NODE_HOST_LOG_FILE
      - GRAFANA_HOST=$GRAFANA_HOST
      - GRAFANA_LOGIN=$GRAFANA_LOGIN
      - GRAFANA_LOG_FILE=$GRAFANA_LOG_FILE
      - CLOUD_HOST=$CLOUD_HOST
      - CLOUD_LOGIN=$CLOUD_LOGIN
      - CLOUD_LOG_FILE=$CLOUD_LOG_FILE