{
 "title": "station_meteo",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Forecast",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "OpenWeatherMap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Delta min/max T°",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  temp_maxc as 'max'\nFROM openweathermap\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    },
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  temp_minc as 'min'\nFROM openweathermap\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  },
  {
   "title": "T° actuelle",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  tempc\nFROM openweathermap\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  },
  {
   "title": "H% actuelle",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  humidity\nFROM openweathermap\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  },
  {
   "title": "Vitesse du vent",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  windspeed\nFROM openweathermap\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  },
  {
   "title": "Direction du vent",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 16 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  winddirection\nFROM openweathermap\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  },
  {
   "title": "SUNRISE",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 16 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  sunrise\nFROM openweathermap\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  },
  {
   "title": "SUNSET",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 16 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  sunset\nFROM openweathermap\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  },
  {
   "title": "Date dernieres données",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date\nFROM openweathermap\nORDER BY id desc limit 1"
    }
   ]
  },
  {
   "title": "Ciel",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  detail\nFROM openweathermap\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  },
  { "title": "Local", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Serveur",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  hum\nFROM Serveur\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    },
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  temp\nFROM Serveur\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  },
  {
   "title": "Bureau",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  hum AS \"Humidité\"\nFROM Bureau\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    },
    {
     "rawSql": "SELECT\n  insert_date AS \"time\",\n  temp AS \"Température\"\nFROM Bureau\nWHERE\n  $__timeFilter(insert_date)\nORDER BY insert_date"
    }
   ]
  }
 ]
}